### PR TITLE
Pysics tests

### PR DESCRIPTION
**Pull request by edoddridge**
Add a layerwise volume conservation test to the current test suite, as per #66.

The test requires volume to be conserved to better than one part in 100,000. For most of the tests this requirement is exceeded by several orders of magnitude.

Momentum and energy checks are proving more difficult, and will be added in a future pull request.

### CODE REVIEW

**Comment by edoddridge** [comment]
Ah. I didn't intend that last set of commits to get added to this pull request. There's nothing really wrong with the code, the tests just aren't ready for prime time and won't give failures. 

I was just trying to keep a branch pushed so that you could see what I was up to, and forgot that I had an open pull request on this branch. It's probably not worth the hassle of fiddling around with the git history to rectify my mistake.

**Comment by axch** [comment]
It's actually pretty easy: Create a new branch at the proper point, and either change this PR to refer to that one, or create a new PR.

Or you could go the other way: push you new commits to a new branch on github, and then force-update this PR's branch to the appropriate place.

**Comment by axch** [comment]
Manually merged the two commits this PR was actually intended for.

Closing this PR itself pending a PR for the further physics-based testing.

**Comment by edoddridge** [comment]
Thanks.

**Pull request closed without merging**
