### PR TITLE
Build exit status

### PR DESCRIPTION
**Pull request by axch**
Pursuant to Issue #7, change the `run_examples.sh` script to emit a failing exit status if any of the compilations or model runs fail.

It currently indeed fails, but I am not sure how to fix it.

### CODE REVIEW

**Comment by axch** [comment]
Ironically, fixing `run_examples.sh` causes this PR to fail Travis checking.  However, it does fix #7.

**Comment by edoddridge** [comment]
It looks like this is failing the test because the `fu.bin` input for the beta_plane_gyre test is the [too small](https://travis-ci.org/edoddridge/MIM/builds/205615936#L233).

**Comment by edoddridge** [comment]
Now that we've confirmed Travis CI will fail if the tests fail, do you want to close #7?

**Comment by edoddridge** [comment]
Well, that's not what I expected. After regenerating the inputs on my laptop the examples all ran perfectly.

**Comment by axch** [comment]
Re: closing #7: I think that the fix #7 annotation in my comment will cause Github to close that ticket when this PR is merged.  Or perhaps an annotation like that needs to appear in the log message of the merge commit, which you may or may not have the option to type in when you merge the PR.  In any case, I strongly prefer that the open/closed status of issues reflect the master branch, so would rather wait to close #7 until this is merged.

**Comment by axch** [comment]
Re: commit discipline: Dunno.  I've never seen anyone do recursive pull requests.  Generally, what people tend to do is commit on top of the PR branch if the PR is "broken" (according to the project's policy), or else merge and then make a separate change if the PR is "acceptable" on its own terms but brings up another issue that needs to be resolved.

Note that in an instance like this, it doesn't make all that much sense to stick with a strict "Travis must always pass on master" policy, because the reason it was passing before this PR is because the build script incorrectly reported a pass in a broken state.

**Comment by axch** [comment]
Speaking of Travis, it seems that it and your laptop disagree about whether the examples run successfully: https://travis-ci.org/edoddridge/MIM/builds/205668869

**Pull request merged**
