### PR TITLE
Refactoring test suite

### PR DESCRIPTION
**Pull request by axch**
Pursuant to Issue #6, rewrote all the examples from the examples/ directory as tests runnable in [pytest](http://doc.pytest.org/en/latest/contents.html).

Specific choices:
- All the test cases have the form "compile MIM, run it on the example, and compare the output to specific known outputs bit for bit."  This is good for sanity-checking refactorings, but creates a maintenance burden for changes that are expected to change the numerics.
- The tests are written to be self-contained, with the minimum necessary version-controlled assets: each test can run independently, and generates all the source, binary, and input files that it needs in order to operate.
- The tests run simulations at ludicrously low resolution.  The purpose is to check that the results are identical from one run to another, as quickly as possible, not to check that they make any sense.

### CODE REVIEW

**Comment by edoddridge** [comment]
This looks great! 

Looking through the changes I had one question: what's behind having "red" at the end of the function names in python? E.g. [`write_input_beta_plane_gyre_red'](https://github.com/edoddridge/MIM/pull/19/files?diff=unified#diff-e581f9d051bfb41f60cc98b0a59db6a0R151)

**Comment by edoddridge** [comment]
I think I've worked it out - it means the reduced gravity version, yes?

**Comment by axch** [comment]
Yes, that naming convention means "reduced gravity".  You having to ask is an object lesson for me in the evils of abbreviations in function names.

**Comment by edoddridge** [comment]
Perhaps "RedGrav" would make more sense? It may also be worth changing the names of the n-layer versions.

**Comment by axch** [comment]
Feel free :)  But, you may have noticed that I prefer my names under_scored rather than CamelCased, so `_red_grav`?

**Comment by edoddridge** [comment]
Sure - snake case works for me.

Running these tests on my laptop I don't get all of them passing. I noticed that you've got the compiler optimisations turned on, and I think that might be the reason. 

Using `-Ofast` I get 2 fails (the beta_plane_gyre tests) and 4 passes in 26 seconds. Switching to `-O1` I get 5 fails and 1 pass (f_plane_red) in 9 seconds. Using no optimisations I get the same result as for `-O1`, but in 4.7 seconds.

My thinking is that there's no point taking the compile time hit to optimise the binaries for such short simulations, and I suspect that the optimisations are to blame for the lack of bit reproducibility.

**Pull request merged**
